### ISSUE TITLE
Plugin no longer compatible with Emby 4.4?

### ISSUE THREAD

**Issue by dapharsyde** [ta264/Emby.MythTv#29]
I've had mixed success with this plugin in the past, and recently gave it another go around.  Unfortunately, when attempting to update the plugin configuration settings, the page that loads just presents a spinning circle - 
![mythtv_plugin](https://user-images.githubusercontent.com/2742390/70871386-a89f9a00-1f53-11ea-9d19-842b5c5509d0.PNG)

I'm unable to save/update the settings.  

LiveTV also does not work - attempting to start playback results in this error: "No compatible streams are currently available. Please try again later or contact your system administrator for details."

However, all recordings found in "Myth TV Recordings" playback fine, so I know the plugin is communicating with Mythbackend properly.

Do you have any insight on why the configuration page and LiveTV are no longer working?

I am using Ubuntu 18.04, Mythbackend .29, and Emby 4.4.0.2

**Comment by ddp526** [comment]
Firstly thanks ta264 for doing this :)   I am keen to get this going but have similar issues...

I had a bit of a look at the code, it seems there are javascript errors in Emby.MythTv/Configuration/configPage.html ... I half hacked it up (based on a commit to nextpvr (https://github.com/MediaBrowser/NextPVR/commit/a32256460b8afddf79bd975f33a50e072b53ee4a#diff-a23a39952026d6daee97c28a71e53cfb) and some jscript knowledge) and I got it to save.   It drops a file into:

/config/plugins/configurations/Emby.MythTv.xml

So as a quick hack, if that file is correct and with the right content, it *seems* like it should connect.  So I am sort of in the same boat as dapharsyde, I can see parts of the plugin working - for me the recording schedules and channel content, but I don't get my recordings, or the guide, or live tv.  

If I get some more spare time I can try to dig further if anyone has a suggestion on where in the code, but its a bit hard without a tip / doco. - and its my first time coding in a windows setup, so I'm a little vague on some of the basics I guess...

BTW, for ta264 / others, the code I changed was to replace the jscript $('#tag') syntax with page.querySelector('#tag'), see an example below:

// removed these 2 lines:
// $('#chkLoadChannelIcons', page).checked(config.LoadChannelIcons || false).checkboxradio("refresh");
              // $('#chkUseSchedulesDirectImages', page).checked(config.UseSchedulesDirectImages || false).checkboxradio("refresh");
                
              // added these 2 lines (to replace the 2 lines above)
              page.querySelector('#chkLoadChannelIcons').checked = config.LoadChannelIcons || false;
              page.querySelector('#chkUseSchedulesDirectImages').checked = config.UseSchedulesDirectImages || false;

**Comment by ta264** [comment]
I haven't tried it with the 4.4 beta but it all works fine with 4.3 for me.  I don't have any immediate plans to look at 4.4 until it's time to upgrade my personal media server...

If you post a debug log of the errors @ddp526 I might be able to give you some pointers

**Comment by ddp526** [comment]
Thank you for the offrer, and I'll do that when I get a few more minutes to spare :)

A quick clarification, I am actually using 4.3 not 4.4 -- sorry, should have looked harder at the issue name.  My quick guess is maybe this is browser specific if you don't see it and we do?

My console errors in my browser show:

Requesting url without automatic networking: http://<host-removed>:8096/emby/Plugins/3a64de78-51be-495e-89de-0bb46f8c28f4/Configuration
VM254:17 Uncaught (in promise) TypeError: $(...).checked is not a function
    at <anonymous>:17:47
for ref: that line is:               $('#chkLoadChannelIcons', page).checked(config.LoadChannelIcons || false).checkboxradio("refresh");


I'm currently running on Linux Mint (just an Ubuntu 18.04 variant), with Emby Server: 4.3.1.0 (via the docker image:  emby/embyserver).  I've used chromium (81.0.4021.2)  and firefox (72.0.1) with the same javascript error.

I am half-confident this issue is not cuasing the actual errors I get in myth not showing some content (as earlier mentioned in the issue, some content is working, so the config file is sufficient - I think - to get the traffic to and from my mythtv-server), but this javascript error stops me setting/changing config via the GUI.

**Comment by ddp526** [comment]
Just made sure I downloaded the latest mythtv emby plugin, and clicked on livetv and myth recordings.  The debug log is attached.

To sum up:
-  The config page gave me javascript errors so the GETs are there but no POSTs in the logs (from what I can see)
-  Programmes, Guide, Channels, Recordings all end with no content
- Schedule and Series work perfectly
- "MythTV Recordings" also has no content

It might be worth mentioning that I have another library called "myth recordings" that is a straight link to my myth tv recordings on the file systems, and I have a script I can run that generates nfo files to give me metadata, its a hack, but at least works if I am desperate :)
[embyserver.txt](https://github.com/ta264/Emby.MythTv/files/4173823/embyserver.txt)

**Comment by eddyg** [comment]
Was any further progress ever made on getting MythTV working in Emby?

I'm a long-time MythTV user and am trying to consolidate everything to one device (Apple TV). A good MythTV front-end (with commercial skipping support!) is the one thing I'm missing. (There is a basic [MythTV app](https://apps.apple.com/us/app/mythtv/id1050385244) for the Apple TV that came out in 2015 and has had some very minor updates over the years to keep it kinda-working, but the playback controls are very frustrating, and it doesn't automatically skip commercials like the actual `mythfrontend` player.) 

Since I already use Emby (now up to version 4.6), a plug-in would be an ideal solution. I'd even settle for just a good, _responsive_ playback-only interface for recorded shows that supported skipping flagged commercials, and rely on the backend web interface for scheduling and such.

**Comment by ta264** [comment]
I have retired my livetv setup, so no unfortunately not.
